# Generated by Django 4.2.9 on 2025-07-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('method', models.CharField(max_length=24)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='herd.cattle')),
            ],
            options={
                'verbose_name': 'Weight log',
                'verbose_name_plural': 'Weight logs',
                'ordering': ['measured_at'],
                'unique_together': {('cattle', 'measured_at')},
            },
        ),
    ]
